### ISSUE TITLE
 assert arguments.config_path is not None, 'Please provide a configuration'\

### ISSUE THREAD

**Issue by molyswu** [LLebronC/M5-mcv#13]
python2.7 train.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 136, in <module>
    main()
  File "train.py", line 105, in main
    assert arguments.config_path is not None, 'Please provide a configuration'\
AssertionError: Please provide a configurationpath using -c config/pathname in the command line

Thank you for your help!

**Comment by JoseLGomez** [comment]
As you can see in the assertion error, you need to provide the configuration file when you run the train.py as an argument using -c and the path of this configuration file. You have an execution sample in the readme: CUDA_VISIBLE_DEVICES=0 python train.py -c config/dataset.py -e expName
