### ISSUE TITLE
some questions about the preprocess of  data for the TT100K database

### ISSUE THREAD

**Issue by lfrcoder** [LLebronC/M5-mcv#14]
I would like to ask some questions： 
Have you done the same preprocessing as original author to preprocess the data for the TT100K database？Such as perspective transformation, as if not mentioned in your experiment.

**Comment by JoseLGomez** [comment]
We didn't follow the original paper preprocesses or data augmentation. The basic configuration used in the experiments for this dataset can be found in /code/config/tt100k_[detection or classification].py, the last two blocks of this file show if we used any preprocessing at all or data aug. Think this was a Master Lab session, we didn't try to replicate papers, only try to make things work and play with hyperparameters.

Regards.

**Comment by lfrcoder** [comment]
Thank you for your answer. I tried the TT100K experiment on YOLO-V3, but the detection was not good. wonder if it is because the pre-processing is different from the original author.
